name: call_manager
description: Call Manager in Flutter
version: 2.8.2+51
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bluejay: ^1.4.0
  cloud_firestore: ^2.2.0
  contacts_service: ^0.6.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  direct_dialer: ^1.0.1+1
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_local_notifications: ^6.0.0
  flutter_typeahead: ^3.1.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  groovin_widgets: ^2.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  package_info: ^2.0.2
  permission_handler: ^8.0.0+2
  provider: ^5.0.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^3.0.0
  timezone: any
  url_launcher: ^6.0.3
  wiredash: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.7.2"
  dart_code_metrics: ^4.0.0-dev.1
  flutter_lints: ^1.0.3

flutter_icons:
  android: true
  #image_path: "assets/icon/call_manager_app_icon.png"
  #adaptive_icon_background: "#1976D2"

flutter:
  uses-material-design: true

  assets:
    - android/app/src/main/res/drawable-hdpi/ic_notification.png
    - assets/icon/call_manager_app_icon.png
    - assets/glogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500
